#!/bin/sh
set -e
exec 2>&1
test `id -u` -gt 0 || exec setuidgid -s deployer-mailer env HOME=`eval echo ~deployer-mailer` "$0" "$@"
cd ./root
export DEPLOYER_CONFIG="/etc/deployer.conf"
exec deployer-mailer-service
