#!/bin/sh
set -e
exec 2>&1
test `id -u` -gt 0 || exec setuidgid -s bouncer env HOME=`eval echo ~bouncer` "$0" "$@"
cd ./root
export DEPLOYER_CONFIG="/etc/deployer.conf"
. "$DEPLOYER_CONFIG"
exec trigger-listen -v -c 1 "$DEPLOYER_BOUNCER_TRIGGER" deployer-bouncer /service
