#!/bin/sh
set -e

. /etc/deployer.conf

# Create privsep users.

getent group bouncer >/dev/null ||
  groupadd bouncer -g 64222
getent passwd bouncer >/dev/null ||
  useradd bouncer --system -u 64222 -g bouncer -c "Bouncer Service" -d /nonexistent -s /usr/sbin/nologin

getent group deployer-mailer >/dev/null ||
  groupadd deployer-mailer -g 64223
getent passwd deployer-mailer >/dev/null ||
  useradd deployer-mailer --system -u 64223 -g deployer-mailer -c "Deployer Mailer Service" -d /nonexistent -s /usr/sbin/nologin

getent group deployer-log >/dev/null ||
  groupadd deployer-log -g 64224
getent passwd deployer-log >/dev/null ||
  useradd deployer-log --system -u 64224 -g deployer-log -c "Deployer Logger" -d /nonexistent -s /usr/sbin/nologin

# Create operator groups.

getent group deployers >/dev/null ||
  groupadd -g 622 deployers

getent group svc-deployer >/dev/null ||
  groupadd -g 623 svc-deployer

getent group svc-deployer-mailer >/dev/null ||
  groupadd -g 624 svc-deployer-mailer

getent group svc-bouncer >/dev/null ||
  groupadd -g 625 svc-bouncer

cat <<EOM
Consider adding operators to the following groups:

deployers
svc-deployer
svc-deployer-mailer
svc-bouncer
EOM

# Create state directories.

install -d -m 0755 -o root            -g root            /var/lib/deployer
install -d -m 0755 -o deployer-mailer -g deployer-mailer /var/lib/deployer-mailer
install -d -m 0755 -o bouncer         -g bouncer         /var/lib/bouncer

test -z "$DEPLOYER_BOUNCED_DIR" ||
  install -d -m 0755 -o bouncer -g bouncer "$DEPLOYER_BOUNCED_DIR"

# Create trigger directories.

test -z "$DEPLOYER_TRIGGER" ||
  install -d -m 0755 -o root -g root "${DEPLOYER_TRIGGER%/*}"
test -z "$DEPLOYER_MAILER_TRIGGER"  ||
  install -d -m 0755 -o deployer-mailer -g deployer-mailer "${DEPLOYER_MAILER_TRIGGER%/*}"
test -z "$DEPLOYER_BOUNCER_TRIGGER" ||
  install -d -m 0755 -o bouncer -g bouncer "${DEPLOYER_BOUNCER_TRIGGER%/*}"

# Create lock file directories.

test -z "$DEPLOYER_UNIT_LOCK_DIR" ||
  install -d -m 0755 -o root -g root "$DEPLOYER_UNIT_LOCK_DIR"

# Create filesystem queue directories.

test -z "$DEPLOYER_QUEUE" || {
  install -d -m 0755 -o root -g root      "$DEPLOYER_QUEUE"
  install -d -m 3775 -o root -g deployers "$DEPLOYER_QUEUE"/tmp
  install -d -m 0755 -o root -g root      "$DEPLOYER_QUEUE"/req
  install -d -m 0755 -o root -g root      "$DEPLOYER_QUEUE"/new
  install -d -m 0755 -o root -g root      "$DEPLOYER_QUEUE"/cur
  install -d -m 0755 -o root -g root      "$DEPLOYER_QUEUE"/fail
}

test -z "$DEPLOYER_MAILER_QUEUE" || {
  install -d -m 0755 -o deployer-mailer -g deployer-mailer "$DEPLOYER_MAILER_QUEUE"
  install -d -m 0755 -o deployer-mailer -g deployer-mailer "$DEPLOYER_MAILER_QUEUE"/tmp
  install -d -m 0755 -o deployer-mailer -g deployer-mailer "$DEPLOYER_MAILER_QUEUE"/new
  install -d -m 0755 -o deployer-mailer -g deployer-mailer "$DEPLOYER_MAILER_QUEUE"/cur
  install -d -m 0755 -o deployer-mailer -g deployer-mailer "$DEPLOYER_MAILER_QUEUE"/fail
}

# Create daemontools state directories.

install -d -m 0755 -o root -g root /var/lib/supervise/deployer
install -d -m 0755 -o root -g root /var/lib/supervise/deployer.log
install -d -m 0755 -o root -g root /var/lib/supervise/deployer-mailer
install -d -m 0755 -o root -g root /var/lib/supervise/deployer-mailer.log
install -d -m 0755 -o root -g root /var/lib/supervise/bouncer
install -d -m 0755 -o root -g root /var/lib/supervise/bouncer.log

# Create log file directories.

install -d -m 0775 -o root -g deployer-log /var/log/deployer
install -d -m 0775 -o root -g deployer-log /var/log/deployer-mailer
install -d -m 0775 -o root -g deployer-log /var/log/bouncer

# Create the managed deployment root.

test -z "$DEPLOYER_DEPLOY_ROOT" ||
  install -d -m 0755 -o root -g root "$DEPLOYER_DEPLOY_ROOT"

