#!/bin/sh
set -e

# TODO source /etc/deployer.conf to get configured locations.

# Create privsep users.

getent passwd bouncer >/dev/null ||
  useradd bouncer -U -c "Bouncer Service" -d /nonexistent -s /usr/sbin/nologin

getent passwd deployer-mailer >/dev/null ||
  useradd deployer-mailer -U -c "Deployer Mailer Service" -d /nonexistent -s /usr/sbin/nologin

getent passwd deployer-log >/dev/null ||
  useradd deployer-log -U -c "Deployer Logger" -d /nonexistent -s /usr/sbin/nologin

# Create groups.
# TODO emit informational message about adding users to these groups.

getent group deployers >/dev/null ||
  groupadd deployers

getent group svc-deployer >/dev/null ||
  groupadd svc-deployer

getent group svc-deployer-mailer >/dev/null ||
  groupadd svc-deployer-mailer

getent group svc-bouncer >/dev/null ||
  groupadd svc-bouncer

# Create state directories.

install -d -m 0755 -o root            -g root            /var/lib/deployer
install -d -m 0755 -o deployer-mailer -g deployer-mailer /var/lib/deployer-mailer
install -d -m 0755 -o bouncer         -g bouncer         /var/lib/bouncer

# Create trigger directories.

install -d -m 0755 -o root            -g root            /var/trigger
install -d -m 0755 -o root            -g root            /var/trigger/deployer
install -d -m 0755 -o deployer-mailer -g deployer-mailer /var/trigger/deployer-mailer
install -d -m 0755 -o bouncer         -g bouncer         /var/trigger/bouncer

# Create lock file directories.

install -d -m 0755 -o root -g root /var/locks/deployer/unit

# Create filesystem queue directories.

install -d -m 0755 -o root            -g root            /var/queue
install -d -m 0755 -o root            -g root            /var/queue/deployer
install -d -m 3775 -o root            -g deployers       /var/queue/deployer/tmp
install -d -m 0755 -o root            -g root            /var/queue/deployer/req
install -d -m 0755 -o root            -g root            /var/queue/deployer/new
install -d -m 0755 -o root            -g root            /var/queue/deployer/cur
install -d -m 0755 -o root            -g root            /var/queue/deployer/fail
install -d -m 0755 -o deployer-mailer -g deployer-mailer /var/queue/deployer-mailer
install -d -m 0755 -o deployer-mailer -g deployer-mailer /var/queue/deployer-mailer/tmp
install -d -m 0755 -o deployer-mailer -g deployer-mailer /var/queue/deployer-mailer/new
install -d -m 0755 -o deployer-mailer -g deployer-mailer /var/queue/deployer-mailer/cur
install -d -m 0755 -o deployer-mailer -g deployer-mailer /var/queue/deployer-mailer/fail

# Create daemontools state directories.

install -d -m 0755 -o root -g root /var/lib/supervise/deployer
install -d -m 0755 -o root -g root /var/lib/supervise/deployer.log
install -d -m 0755 -o root -g root /var/lib/supervise/deployer-mailer
install -d -m 0755 -o root -g root /var/lib/supervise/deployer-mailer.log
install -d -m 0755 -o root -g root /var/lib/supervise/bouncer
install -d -m 0755 -o root -g root /var/lib/supervise/bouncer.log

# Create log file directories.

install -d -m 0775 -o root -g deployer-log /var/log/deployer
install -d -m 0775 -o root -g deployer-log /var/log/deployer-mailer
install -d -m 0775 -o root -g deployer-log /var/log/bouncer

# TODO install and enable the service using `/usr/sbin/update-service`?

